name: test_macos

on: [push, pull_request]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [macos-latest]
        generator: [xcode]
        config: [debug, release]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.generator }}-${{ matrix.config }} (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v3
      - uses: lukka/get-cmake@latest
      - name: Configure
        run: cmake --preset ${{ matrix.generator }}
      - name: Build
        run: cmake --build --preset ${{ matrix.generator }}-${{ matrix.config }} --target bezier-tests
      - name: Test
        run: ctest --preset ${{ matrix.generator }}-${{ matrix.config }}
